/*
gRPC for our DBaaS central service

notably uses gRPC-Gateway with OpenAPI

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package coreportalapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ClusterServicePrecheckAuditLogConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterServicePrecheckAuditLogConfigRequest{}

// ClusterServicePrecheckAuditLogConfigRequest struct for ClusterServicePrecheckAuditLogConfigRequest
type ClusterServicePrecheckAuditLogConfigRequest struct {
	AuditLogConfig CentralAuditLogConfig `json:"audit_log_config"`
}

type _ClusterServicePrecheckAuditLogConfigRequest ClusterServicePrecheckAuditLogConfigRequest

// NewClusterServicePrecheckAuditLogConfigRequest instantiates a new ClusterServicePrecheckAuditLogConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterServicePrecheckAuditLogConfigRequest(auditLogConfig CentralAuditLogConfig) *ClusterServicePrecheckAuditLogConfigRequest {
	this := ClusterServicePrecheckAuditLogConfigRequest{}
	this.AuditLogConfig = auditLogConfig
	return &this
}

// NewClusterServicePrecheckAuditLogConfigRequestWithDefaults instantiates a new ClusterServicePrecheckAuditLogConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterServicePrecheckAuditLogConfigRequestWithDefaults() *ClusterServicePrecheckAuditLogConfigRequest {
	this := ClusterServicePrecheckAuditLogConfigRequest{}
	return &this
}

// GetAuditLogConfig returns the AuditLogConfig field value
func (o *ClusterServicePrecheckAuditLogConfigRequest) GetAuditLogConfig() CentralAuditLogConfig {
	if o == nil {
		var ret CentralAuditLogConfig
		return ret
	}

	return o.AuditLogConfig
}

// GetAuditLogConfigOk returns a tuple with the AuditLogConfig field value
// and a boolean to check if the value has been set.
func (o *ClusterServicePrecheckAuditLogConfigRequest) GetAuditLogConfigOk() (*CentralAuditLogConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuditLogConfig, true
}

// SetAuditLogConfig sets field value
func (o *ClusterServicePrecheckAuditLogConfigRequest) SetAuditLogConfig(v CentralAuditLogConfig) {
	o.AuditLogConfig = v
}

func (o ClusterServicePrecheckAuditLogConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterServicePrecheckAuditLogConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["audit_log_config"] = o.AuditLogConfig
	return toSerialize, nil
}

func (o *ClusterServicePrecheckAuditLogConfigRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"audit_log_config",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterServicePrecheckAuditLogConfigRequest := _ClusterServicePrecheckAuditLogConfigRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClusterServicePrecheckAuditLogConfigRequest)

	if err != nil {
		return err
	}

	*o = ClusterServicePrecheckAuditLogConfigRequest(varClusterServicePrecheckAuditLogConfigRequest)

	return err
}

type NullableClusterServicePrecheckAuditLogConfigRequest struct {
	value *ClusterServicePrecheckAuditLogConfigRequest
	isSet bool
}

func (v NullableClusterServicePrecheckAuditLogConfigRequest) Get() *ClusterServicePrecheckAuditLogConfigRequest {
	return v.value
}

func (v *NullableClusterServicePrecheckAuditLogConfigRequest) Set(val *ClusterServicePrecheckAuditLogConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterServicePrecheckAuditLogConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterServicePrecheckAuditLogConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterServicePrecheckAuditLogConfigRequest(val *ClusterServicePrecheckAuditLogConfigRequest) *NullableClusterServicePrecheckAuditLogConfigRequest {
	return &NullableClusterServicePrecheckAuditLogConfigRequest{value: val, isSet: true}
}

func (v NullableClusterServicePrecheckAuditLogConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterServicePrecheckAuditLogConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
