/*
gRPC for our DBaaS central service

notably uses gRPC-Gateway with OpenAPI

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package coreportalapi

import (
	"encoding/json"
)

// checks if the CentralCreateAuditLogAccessRecordResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CentralCreateAuditLogAccessRecordResp{}

// CentralCreateAuditLogAccessRecordResp struct for CentralCreateAuditLogAccessRecordResp
type CentralCreateAuditLogAccessRecordResp struct {
	BaseResp *CentralBaseResp `json:"base_resp,omitempty"`
}

// NewCentralCreateAuditLogAccessRecordResp instantiates a new CentralCreateAuditLogAccessRecordResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCentralCreateAuditLogAccessRecordResp() *CentralCreateAuditLogAccessRecordResp {
	this := CentralCreateAuditLogAccessRecordResp{}
	return &this
}

// NewCentralCreateAuditLogAccessRecordRespWithDefaults instantiates a new CentralCreateAuditLogAccessRecordResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCentralCreateAuditLogAccessRecordRespWithDefaults() *CentralCreateAuditLogAccessRecordResp {
	this := CentralCreateAuditLogAccessRecordResp{}
	return &this
}

// GetBaseResp returns the BaseResp field value if set, zero value otherwise.
func (o *CentralCreateAuditLogAccessRecordResp) GetBaseResp() CentralBaseResp {
	if o == nil || IsNil(o.BaseResp) {
		var ret CentralBaseResp
		return ret
	}
	return *o.BaseResp
}

// GetBaseRespOk returns a tuple with the BaseResp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CentralCreateAuditLogAccessRecordResp) GetBaseRespOk() (*CentralBaseResp, bool) {
	if o == nil || IsNil(o.BaseResp) {
		return nil, false
	}
	return o.BaseResp, true
}

// HasBaseResp returns a boolean if a field has been set.
func (o *CentralCreateAuditLogAccessRecordResp) HasBaseResp() bool {
	if o != nil && !IsNil(o.BaseResp) {
		return true
	}

	return false
}

// SetBaseResp gets a reference to the given CentralBaseResp and assigns it to the BaseResp field.
func (o *CentralCreateAuditLogAccessRecordResp) SetBaseResp(v CentralBaseResp) {
	o.BaseResp = &v
}

func (o CentralCreateAuditLogAccessRecordResp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CentralCreateAuditLogAccessRecordResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BaseResp) {
		toSerialize["base_resp"] = o.BaseResp
	}
	return toSerialize, nil
}

type NullableCentralCreateAuditLogAccessRecordResp struct {
	value *CentralCreateAuditLogAccessRecordResp
	isSet bool
}

func (v NullableCentralCreateAuditLogAccessRecordResp) Get() *CentralCreateAuditLogAccessRecordResp {
	return v.value
}

func (v *NullableCentralCreateAuditLogAccessRecordResp) Set(val *CentralCreateAuditLogAccessRecordResp) {
	v.value = val
	v.isSet = true
}

func (v NullableCentralCreateAuditLogAccessRecordResp) IsSet() bool {
	return v.isSet
}

func (v *NullableCentralCreateAuditLogAccessRecordResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCentralCreateAuditLogAccessRecordResp(val *CentralCreateAuditLogAccessRecordResp) *NullableCentralCreateAuditLogAccessRecordResp {
	return &NullableCentralCreateAuditLogAccessRecordResp{value: val, isSet: true}
}

func (v NullableCentralCreateAuditLogAccessRecordResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCentralCreateAuditLogAccessRecordResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
