/*
gRPC for our DBaaS central service

notably uses gRPC-Gateway with OpenAPI

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package coreportalapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CentralGcpVpcPeerings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CentralGcpVpcPeerings{}

// CentralGcpVpcPeerings struct for CentralGcpVpcPeerings
type CentralGcpVpcPeerings struct {
	Total int32                  `json:"total"`
	Items []CentralGcpVpcPeering `json:"items"`
}

type _CentralGcpVpcPeerings CentralGcpVpcPeerings

// NewCentralGcpVpcPeerings instantiates a new CentralGcpVpcPeerings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCentralGcpVpcPeerings(total int32, items []CentralGcpVpcPeering) *CentralGcpVpcPeerings {
	this := CentralGcpVpcPeerings{}
	this.Total = total
	this.Items = items
	return &this
}

// NewCentralGcpVpcPeeringsWithDefaults instantiates a new CentralGcpVpcPeerings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCentralGcpVpcPeeringsWithDefaults() *CentralGcpVpcPeerings {
	this := CentralGcpVpcPeerings{}
	return &this
}

// GetTotal returns the Total field value
func (o *CentralGcpVpcPeerings) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *CentralGcpVpcPeerings) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *CentralGcpVpcPeerings) SetTotal(v int32) {
	o.Total = v
}

// GetItems returns the Items field value
func (o *CentralGcpVpcPeerings) GetItems() []CentralGcpVpcPeering {
	if o == nil {
		var ret []CentralGcpVpcPeering
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *CentralGcpVpcPeerings) GetItemsOk() ([]CentralGcpVpcPeering, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *CentralGcpVpcPeerings) SetItems(v []CentralGcpVpcPeering) {
	o.Items = v
}

func (o CentralGcpVpcPeerings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CentralGcpVpcPeerings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *CentralGcpVpcPeerings) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total",
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCentralGcpVpcPeerings := _CentralGcpVpcPeerings{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCentralGcpVpcPeerings)

	if err != nil {
		return err
	}

	*o = CentralGcpVpcPeerings(varCentralGcpVpcPeerings)

	return err
}

type NullableCentralGcpVpcPeerings struct {
	value *CentralGcpVpcPeerings
	isSet bool
}

func (v NullableCentralGcpVpcPeerings) Get() *CentralGcpVpcPeerings {
	return v.value
}

func (v *NullableCentralGcpVpcPeerings) Set(val *CentralGcpVpcPeerings) {
	v.value = val
	v.isSet = true
}

func (v NullableCentralGcpVpcPeerings) IsSet() bool {
	return v.isSet
}

func (v *NullableCentralGcpVpcPeerings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCentralGcpVpcPeerings(val *CentralGcpVpcPeerings) *NullableCentralGcpVpcPeerings {
	return &NullableCentralGcpVpcPeerings{value: val, isSet: true}
}

func (v NullableCentralGcpVpcPeerings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCentralGcpVpcPeerings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
