/*
gRPC for our DBaaS central service

notably uses gRPC-Gateway with OpenAPI

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package coreportalapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CentralUpdateProjectMaintenanceWindowResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CentralUpdateProjectMaintenanceWindowResp{}

// CentralUpdateProjectMaintenanceWindowResp struct for CentralUpdateProjectMaintenanceWindowResp
type CentralUpdateProjectMaintenanceWindowResp struct {
	UnchangedTasks []CentralUnchangedTask `json:"unchanged_tasks,omitempty"`
	BaseResp       CentralBaseResp        `json:"base_resp"`
}

type _CentralUpdateProjectMaintenanceWindowResp CentralUpdateProjectMaintenanceWindowResp

// NewCentralUpdateProjectMaintenanceWindowResp instantiates a new CentralUpdateProjectMaintenanceWindowResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCentralUpdateProjectMaintenanceWindowResp(baseResp CentralBaseResp) *CentralUpdateProjectMaintenanceWindowResp {
	this := CentralUpdateProjectMaintenanceWindowResp{}
	this.BaseResp = baseResp
	return &this
}

// NewCentralUpdateProjectMaintenanceWindowRespWithDefaults instantiates a new CentralUpdateProjectMaintenanceWindowResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCentralUpdateProjectMaintenanceWindowRespWithDefaults() *CentralUpdateProjectMaintenanceWindowResp {
	this := CentralUpdateProjectMaintenanceWindowResp{}
	return &this
}

// GetUnchangedTasks returns the UnchangedTasks field value if set, zero value otherwise.
func (o *CentralUpdateProjectMaintenanceWindowResp) GetUnchangedTasks() []CentralUnchangedTask {
	if o == nil || IsNil(o.UnchangedTasks) {
		var ret []CentralUnchangedTask
		return ret
	}
	return o.UnchangedTasks
}

// GetUnchangedTasksOk returns a tuple with the UnchangedTasks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CentralUpdateProjectMaintenanceWindowResp) GetUnchangedTasksOk() ([]CentralUnchangedTask, bool) {
	if o == nil || IsNil(o.UnchangedTasks) {
		return nil, false
	}
	return o.UnchangedTasks, true
}

// HasUnchangedTasks returns a boolean if a field has been set.
func (o *CentralUpdateProjectMaintenanceWindowResp) HasUnchangedTasks() bool {
	if o != nil && !IsNil(o.UnchangedTasks) {
		return true
	}

	return false
}

// SetUnchangedTasks gets a reference to the given []CentralUnchangedTask and assigns it to the UnchangedTasks field.
func (o *CentralUpdateProjectMaintenanceWindowResp) SetUnchangedTasks(v []CentralUnchangedTask) {
	o.UnchangedTasks = v
}

// GetBaseResp returns the BaseResp field value
func (o *CentralUpdateProjectMaintenanceWindowResp) GetBaseResp() CentralBaseResp {
	if o == nil {
		var ret CentralBaseResp
		return ret
	}

	return o.BaseResp
}

// GetBaseRespOk returns a tuple with the BaseResp field value
// and a boolean to check if the value has been set.
func (o *CentralUpdateProjectMaintenanceWindowResp) GetBaseRespOk() (*CentralBaseResp, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseResp, true
}

// SetBaseResp sets field value
func (o *CentralUpdateProjectMaintenanceWindowResp) SetBaseResp(v CentralBaseResp) {
	o.BaseResp = v
}

func (o CentralUpdateProjectMaintenanceWindowResp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CentralUpdateProjectMaintenanceWindowResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UnchangedTasks) {
		toSerialize["unchanged_tasks"] = o.UnchangedTasks
	}
	toSerialize["base_resp"] = o.BaseResp
	return toSerialize, nil
}

func (o *CentralUpdateProjectMaintenanceWindowResp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"base_resp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCentralUpdateProjectMaintenanceWindowResp := _CentralUpdateProjectMaintenanceWindowResp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCentralUpdateProjectMaintenanceWindowResp)

	if err != nil {
		return err
	}

	*o = CentralUpdateProjectMaintenanceWindowResp(varCentralUpdateProjectMaintenanceWindowResp)

	return err
}

type NullableCentralUpdateProjectMaintenanceWindowResp struct {
	value *CentralUpdateProjectMaintenanceWindowResp
	isSet bool
}

func (v NullableCentralUpdateProjectMaintenanceWindowResp) Get() *CentralUpdateProjectMaintenanceWindowResp {
	return v.value
}

func (v *NullableCentralUpdateProjectMaintenanceWindowResp) Set(val *CentralUpdateProjectMaintenanceWindowResp) {
	v.value = val
	v.isSet = true
}

func (v NullableCentralUpdateProjectMaintenanceWindowResp) IsSet() bool {
	return v.isSet
}

func (v *NullableCentralUpdateProjectMaintenanceWindowResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCentralUpdateProjectMaintenanceWindowResp(val *CentralUpdateProjectMaintenanceWindowResp) *NullableCentralUpdateProjectMaintenanceWindowResp {
	return &NullableCentralUpdateProjectMaintenanceWindowResp{value: val, isSet: true}
}

func (v NullableCentralUpdateProjectMaintenanceWindowResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCentralUpdateProjectMaintenanceWindowResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
