/*
gRPC for our DBaaS central service

notably uses gRPC-Gateway with OpenAPI

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package coreportalapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CentralLastError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CentralLastError{}

// CentralLastError struct for CentralLastError
type CentralLastError struct {
	Codes []CentralInfraErrorCode `json:"codes"`
}

type _CentralLastError CentralLastError

// NewCentralLastError instantiates a new CentralLastError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCentralLastError(codes []CentralInfraErrorCode) *CentralLastError {
	this := CentralLastError{}
	this.Codes = codes
	return &this
}

// NewCentralLastErrorWithDefaults instantiates a new CentralLastError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCentralLastErrorWithDefaults() *CentralLastError {
	this := CentralLastError{}
	return &this
}

// GetCodes returns the Codes field value
func (o *CentralLastError) GetCodes() []CentralInfraErrorCode {
	if o == nil {
		var ret []CentralInfraErrorCode
		return ret
	}

	return o.Codes
}

// GetCodesOk returns a tuple with the Codes field value
// and a boolean to check if the value has been set.
func (o *CentralLastError) GetCodesOk() ([]CentralInfraErrorCode, bool) {
	if o == nil {
		return nil, false
	}
	return o.Codes, true
}

// SetCodes sets field value
func (o *CentralLastError) SetCodes(v []CentralInfraErrorCode) {
	o.Codes = v
}

func (o CentralLastError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CentralLastError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["codes"] = o.Codes
	return toSerialize, nil
}

func (o *CentralLastError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"codes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCentralLastError := _CentralLastError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCentralLastError)

	if err != nil {
		return err
	}

	*o = CentralLastError(varCentralLastError)

	return err
}

type NullableCentralLastError struct {
	value *CentralLastError
	isSet bool
}

func (v NullableCentralLastError) Get() *CentralLastError {
	return v.value
}

func (v *NullableCentralLastError) Set(val *CentralLastError) {
	v.value = val
	v.isSet = true
}

func (v NullableCentralLastError) IsSet() bool {
	return v.isSet
}

func (v *NullableCentralLastError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCentralLastError(val *CentralLastError) *NullableCentralLastError {
	return &NullableCentralLastError{value: val, isSet: true}
}

func (v NullableCentralLastError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCentralLastError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
