/*
gRPC for our DBaaS central service

notably uses gRPC-Gateway with OpenAPI

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package coreportalapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CentralTiFlashNode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CentralTiFlashNode{}

// CentralTiFlashNode struct for CentralTiFlashNode
type CentralTiFlashNode struct {
	Name      string                   `json:"name"`
	Status    CentralTiFlashNodeStatus `json:"status"`
	Az        string                   `json:"az"`
	Compute   CentralCompute           `json:"compute"`
	StorageGi int64                    `json:"storage_gi"`
	Type      CentralTiFlashNodeType   `json:"type"`
}

type _CentralTiFlashNode CentralTiFlashNode

// NewCentralTiFlashNode instantiates a new CentralTiFlashNode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCentralTiFlashNode(name string, status CentralTiFlashNodeStatus, az string, compute CentralCompute, storageGi int64, type_ CentralTiFlashNodeType) *CentralTiFlashNode {
	this := CentralTiFlashNode{}
	this.Name = name
	this.Status = status
	this.Az = az
	this.Compute = compute
	this.StorageGi = storageGi
	this.Type = type_
	return &this
}

// NewCentralTiFlashNodeWithDefaults instantiates a new CentralTiFlashNode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCentralTiFlashNodeWithDefaults() *CentralTiFlashNode {
	this := CentralTiFlashNode{}
	var status CentralTiFlashNodeStatus = CENTRALTIFLASHNODESTATUS_AVAILABLE
	this.Status = status
	var type_ CentralTiFlashNodeType = CENTRALTIFLASHNODETYPE_STORAGE
	this.Type = type_
	return &this
}

// GetName returns the Name field value
func (o *CentralTiFlashNode) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CentralTiFlashNode) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CentralTiFlashNode) SetName(v string) {
	o.Name = v
}

// GetStatus returns the Status field value
func (o *CentralTiFlashNode) GetStatus() CentralTiFlashNodeStatus {
	if o == nil {
		var ret CentralTiFlashNodeStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CentralTiFlashNode) GetStatusOk() (*CentralTiFlashNodeStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CentralTiFlashNode) SetStatus(v CentralTiFlashNodeStatus) {
	o.Status = v
}

// GetAz returns the Az field value
func (o *CentralTiFlashNode) GetAz() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Az
}

// GetAzOk returns a tuple with the Az field value
// and a boolean to check if the value has been set.
func (o *CentralTiFlashNode) GetAzOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Az, true
}

// SetAz sets field value
func (o *CentralTiFlashNode) SetAz(v string) {
	o.Az = v
}

// GetCompute returns the Compute field value
func (o *CentralTiFlashNode) GetCompute() CentralCompute {
	if o == nil {
		var ret CentralCompute
		return ret
	}

	return o.Compute
}

// GetComputeOk returns a tuple with the Compute field value
// and a boolean to check if the value has been set.
func (o *CentralTiFlashNode) GetComputeOk() (*CentralCompute, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Compute, true
}

// SetCompute sets field value
func (o *CentralTiFlashNode) SetCompute(v CentralCompute) {
	o.Compute = v
}

// GetStorageGi returns the StorageGi field value
func (o *CentralTiFlashNode) GetStorageGi() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.StorageGi
}

// GetStorageGiOk returns a tuple with the StorageGi field value
// and a boolean to check if the value has been set.
func (o *CentralTiFlashNode) GetStorageGiOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageGi, true
}

// SetStorageGi sets field value
func (o *CentralTiFlashNode) SetStorageGi(v int64) {
	o.StorageGi = v
}

// GetType returns the Type field value
func (o *CentralTiFlashNode) GetType() CentralTiFlashNodeType {
	if o == nil {
		var ret CentralTiFlashNodeType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CentralTiFlashNode) GetTypeOk() (*CentralTiFlashNodeType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CentralTiFlashNode) SetType(v CentralTiFlashNodeType) {
	o.Type = v
}

func (o CentralTiFlashNode) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CentralTiFlashNode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["status"] = o.Status
	toSerialize["az"] = o.Az
	toSerialize["compute"] = o.Compute
	toSerialize["storage_gi"] = o.StorageGi
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *CentralTiFlashNode) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"status",
		"az",
		"compute",
		"storage_gi",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCentralTiFlashNode := _CentralTiFlashNode{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCentralTiFlashNode)

	if err != nil {
		return err
	}

	*o = CentralTiFlashNode(varCentralTiFlashNode)

	return err
}

type NullableCentralTiFlashNode struct {
	value *CentralTiFlashNode
	isSet bool
}

func (v NullableCentralTiFlashNode) Get() *CentralTiFlashNode {
	return v.value
}

func (v *NullableCentralTiFlashNode) Set(val *CentralTiFlashNode) {
	v.value = val
	v.isSet = true
}

func (v NullableCentralTiFlashNode) IsSet() bool {
	return v.isSet
}

func (v *NullableCentralTiFlashNode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCentralTiFlashNode(val *CentralTiFlashNode) *NullableCentralTiFlashNode {
	return &NullableCentralTiFlashNode{value: val, isSet: true}
}

func (v NullableCentralTiFlashNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCentralTiFlashNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
