/*
gRPC for our DBaaS central service

notably uses gRPC-Gateway with OpenAPI

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package coreportalapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CentralCreatePrivateLinkServiceResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CentralCreatePrivateLinkServiceResp{}

// CentralCreatePrivateLinkServiceResp struct for CentralCreatePrivateLinkServiceResp
type CentralCreatePrivateLinkServiceResp struct {
	PrivatelinkService CentralPrivateLinkService `json:"privatelink_service"`
	BaseResp           CentralBaseResp           `json:"base_resp"`
}

type _CentralCreatePrivateLinkServiceResp CentralCreatePrivateLinkServiceResp

// NewCentralCreatePrivateLinkServiceResp instantiates a new CentralCreatePrivateLinkServiceResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCentralCreatePrivateLinkServiceResp(privatelinkService CentralPrivateLinkService, baseResp CentralBaseResp) *CentralCreatePrivateLinkServiceResp {
	this := CentralCreatePrivateLinkServiceResp{}
	this.PrivatelinkService = privatelinkService
	this.BaseResp = baseResp
	return &this
}

// NewCentralCreatePrivateLinkServiceRespWithDefaults instantiates a new CentralCreatePrivateLinkServiceResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCentralCreatePrivateLinkServiceRespWithDefaults() *CentralCreatePrivateLinkServiceResp {
	this := CentralCreatePrivateLinkServiceResp{}
	return &this
}

// GetPrivatelinkService returns the PrivatelinkService field value
func (o *CentralCreatePrivateLinkServiceResp) GetPrivatelinkService() CentralPrivateLinkService {
	if o == nil {
		var ret CentralPrivateLinkService
		return ret
	}

	return o.PrivatelinkService
}

// GetPrivatelinkServiceOk returns a tuple with the PrivatelinkService field value
// and a boolean to check if the value has been set.
func (o *CentralCreatePrivateLinkServiceResp) GetPrivatelinkServiceOk() (*CentralPrivateLinkService, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrivatelinkService, true
}

// SetPrivatelinkService sets field value
func (o *CentralCreatePrivateLinkServiceResp) SetPrivatelinkService(v CentralPrivateLinkService) {
	o.PrivatelinkService = v
}

// GetBaseResp returns the BaseResp field value
func (o *CentralCreatePrivateLinkServiceResp) GetBaseResp() CentralBaseResp {
	if o == nil {
		var ret CentralBaseResp
		return ret
	}

	return o.BaseResp
}

// GetBaseRespOk returns a tuple with the BaseResp field value
// and a boolean to check if the value has been set.
func (o *CentralCreatePrivateLinkServiceResp) GetBaseRespOk() (*CentralBaseResp, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseResp, true
}

// SetBaseResp sets field value
func (o *CentralCreatePrivateLinkServiceResp) SetBaseResp(v CentralBaseResp) {
	o.BaseResp = v
}

func (o CentralCreatePrivateLinkServiceResp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CentralCreatePrivateLinkServiceResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["privatelink_service"] = o.PrivatelinkService
	toSerialize["base_resp"] = o.BaseResp
	return toSerialize, nil
}

func (o *CentralCreatePrivateLinkServiceResp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"privatelink_service",
		"base_resp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCentralCreatePrivateLinkServiceResp := _CentralCreatePrivateLinkServiceResp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCentralCreatePrivateLinkServiceResp)

	if err != nil {
		return err
	}

	*o = CentralCreatePrivateLinkServiceResp(varCentralCreatePrivateLinkServiceResp)

	return err
}

type NullableCentralCreatePrivateLinkServiceResp struct {
	value *CentralCreatePrivateLinkServiceResp
	isSet bool
}

func (v NullableCentralCreatePrivateLinkServiceResp) Get() *CentralCreatePrivateLinkServiceResp {
	return v.value
}

func (v *NullableCentralCreatePrivateLinkServiceResp) Set(val *CentralCreatePrivateLinkServiceResp) {
	v.value = val
	v.isSet = true
}

func (v NullableCentralCreatePrivateLinkServiceResp) IsSet() bool {
	return v.isSet
}

func (v *NullableCentralCreatePrivateLinkServiceResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCentralCreatePrivateLinkServiceResp(val *CentralCreatePrivateLinkServiceResp) *NullableCentralCreatePrivateLinkServiceResp {
	return &NullableCentralCreatePrivateLinkServiceResp{value: val, isSet: true}
}

func (v NullableCentralCreatePrivateLinkServiceResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCentralCreatePrivateLinkServiceResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
