/*
gRPC for our DBaaS central service

notably uses gRPC-Gateway with OpenAPI

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package coreportalapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CentralTrafficFilterResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CentralTrafficFilterResp{}

// CentralTrafficFilterResp struct for CentralTrafficFilterResp
type CentralTrafficFilterResp struct {
	Total          int32                    `json:"total"`
	TrafficFilters CentralTrafficFilterList `json:"traffic_filters"`
}

type _CentralTrafficFilterResp CentralTrafficFilterResp

// NewCentralTrafficFilterResp instantiates a new CentralTrafficFilterResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCentralTrafficFilterResp(total int32, trafficFilters CentralTrafficFilterList) *CentralTrafficFilterResp {
	this := CentralTrafficFilterResp{}
	this.Total = total
	this.TrafficFilters = trafficFilters
	return &this
}

// NewCentralTrafficFilterRespWithDefaults instantiates a new CentralTrafficFilterResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCentralTrafficFilterRespWithDefaults() *CentralTrafficFilterResp {
	this := CentralTrafficFilterResp{}
	return &this
}

// GetTotal returns the Total field value
func (o *CentralTrafficFilterResp) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *CentralTrafficFilterResp) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *CentralTrafficFilterResp) SetTotal(v int32) {
	o.Total = v
}

// GetTrafficFilters returns the TrafficFilters field value
func (o *CentralTrafficFilterResp) GetTrafficFilters() CentralTrafficFilterList {
	if o == nil {
		var ret CentralTrafficFilterList
		return ret
	}

	return o.TrafficFilters
}

// GetTrafficFiltersOk returns a tuple with the TrafficFilters field value
// and a boolean to check if the value has been set.
func (o *CentralTrafficFilterResp) GetTrafficFiltersOk() (*CentralTrafficFilterList, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrafficFilters, true
}

// SetTrafficFilters sets field value
func (o *CentralTrafficFilterResp) SetTrafficFilters(v CentralTrafficFilterList) {
	o.TrafficFilters = v
}

func (o CentralTrafficFilterResp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CentralTrafficFilterResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	toSerialize["traffic_filters"] = o.TrafficFilters
	return toSerialize, nil
}

func (o *CentralTrafficFilterResp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total",
		"traffic_filters",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCentralTrafficFilterResp := _CentralTrafficFilterResp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCentralTrafficFilterResp)

	if err != nil {
		return err
	}

	*o = CentralTrafficFilterResp(varCentralTrafficFilterResp)

	return err
}

type NullableCentralTrafficFilterResp struct {
	value *CentralTrafficFilterResp
	isSet bool
}

func (v NullableCentralTrafficFilterResp) Get() *CentralTrafficFilterResp {
	return v.value
}

func (v *NullableCentralTrafficFilterResp) Set(val *CentralTrafficFilterResp) {
	v.value = val
	v.isSet = true
}

func (v NullableCentralTrafficFilterResp) IsSet() bool {
	return v.isSet
}

func (v *NullableCentralTrafficFilterResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCentralTrafficFilterResp(val *CentralTrafficFilterResp) *NullableCentralTrafficFilterResp {
	return &NullableCentralTrafficFilterResp{value: val, isSet: true}
}

func (v NullableCentralTrafficFilterResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCentralTrafficFilterResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
