/*
gRPC for our DBaaS central service

notably uses gRPC-Gateway with OpenAPI

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package coreportalapi

import (
	"encoding/json"
)

// checks if the CentralClusterNodeProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CentralClusterNodeProfile{}

// CentralClusterNodeProfile struct for CentralClusterNodeProfile
type CentralClusterNodeProfile struct {
	Name                 *string `json:"name,omitempty"`
	DisplayName          *string `json:"display_name,omitempty"`
	DefaultNodeNum       *int32  `json:"default_node_num,omitempty"`
	MinStorageSizeGi     *int32  `json:"min_storage_size_gi,omitempty"`
	MaxStorageSizeGi     *int32  `json:"max_storage_size_gi,omitempty"`
	DefaultStorageSizeGi *int32  `json:"default_storage_size_gi,omitempty"`
	CpuNum               *int32  `json:"cpu_num,omitempty"`
	MemoryGi             *int32  `json:"memory_gi,omitempty"`
}

// NewCentralClusterNodeProfile instantiates a new CentralClusterNodeProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCentralClusterNodeProfile() *CentralClusterNodeProfile {
	this := CentralClusterNodeProfile{}
	return &this
}

// NewCentralClusterNodeProfileWithDefaults instantiates a new CentralClusterNodeProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCentralClusterNodeProfileWithDefaults() *CentralClusterNodeProfile {
	this := CentralClusterNodeProfile{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CentralClusterNodeProfile) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CentralClusterNodeProfile) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CentralClusterNodeProfile) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CentralClusterNodeProfile) SetName(v string) {
	o.Name = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *CentralClusterNodeProfile) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CentralClusterNodeProfile) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *CentralClusterNodeProfile) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *CentralClusterNodeProfile) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDefaultNodeNum returns the DefaultNodeNum field value if set, zero value otherwise.
func (o *CentralClusterNodeProfile) GetDefaultNodeNum() int32 {
	if o == nil || IsNil(o.DefaultNodeNum) {
		var ret int32
		return ret
	}
	return *o.DefaultNodeNum
}

// GetDefaultNodeNumOk returns a tuple with the DefaultNodeNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CentralClusterNodeProfile) GetDefaultNodeNumOk() (*int32, bool) {
	if o == nil || IsNil(o.DefaultNodeNum) {
		return nil, false
	}
	return o.DefaultNodeNum, true
}

// HasDefaultNodeNum returns a boolean if a field has been set.
func (o *CentralClusterNodeProfile) HasDefaultNodeNum() bool {
	if o != nil && !IsNil(o.DefaultNodeNum) {
		return true
	}

	return false
}

// SetDefaultNodeNum gets a reference to the given int32 and assigns it to the DefaultNodeNum field.
func (o *CentralClusterNodeProfile) SetDefaultNodeNum(v int32) {
	o.DefaultNodeNum = &v
}

// GetMinStorageSizeGi returns the MinStorageSizeGi field value if set, zero value otherwise.
func (o *CentralClusterNodeProfile) GetMinStorageSizeGi() int32 {
	if o == nil || IsNil(o.MinStorageSizeGi) {
		var ret int32
		return ret
	}
	return *o.MinStorageSizeGi
}

// GetMinStorageSizeGiOk returns a tuple with the MinStorageSizeGi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CentralClusterNodeProfile) GetMinStorageSizeGiOk() (*int32, bool) {
	if o == nil || IsNil(o.MinStorageSizeGi) {
		return nil, false
	}
	return o.MinStorageSizeGi, true
}

// HasMinStorageSizeGi returns a boolean if a field has been set.
func (o *CentralClusterNodeProfile) HasMinStorageSizeGi() bool {
	if o != nil && !IsNil(o.MinStorageSizeGi) {
		return true
	}

	return false
}

// SetMinStorageSizeGi gets a reference to the given int32 and assigns it to the MinStorageSizeGi field.
func (o *CentralClusterNodeProfile) SetMinStorageSizeGi(v int32) {
	o.MinStorageSizeGi = &v
}

// GetMaxStorageSizeGi returns the MaxStorageSizeGi field value if set, zero value otherwise.
func (o *CentralClusterNodeProfile) GetMaxStorageSizeGi() int32 {
	if o == nil || IsNil(o.MaxStorageSizeGi) {
		var ret int32
		return ret
	}
	return *o.MaxStorageSizeGi
}

// GetMaxStorageSizeGiOk returns a tuple with the MaxStorageSizeGi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CentralClusterNodeProfile) GetMaxStorageSizeGiOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxStorageSizeGi) {
		return nil, false
	}
	return o.MaxStorageSizeGi, true
}

// HasMaxStorageSizeGi returns a boolean if a field has been set.
func (o *CentralClusterNodeProfile) HasMaxStorageSizeGi() bool {
	if o != nil && !IsNil(o.MaxStorageSizeGi) {
		return true
	}

	return false
}

// SetMaxStorageSizeGi gets a reference to the given int32 and assigns it to the MaxStorageSizeGi field.
func (o *CentralClusterNodeProfile) SetMaxStorageSizeGi(v int32) {
	o.MaxStorageSizeGi = &v
}

// GetDefaultStorageSizeGi returns the DefaultStorageSizeGi field value if set, zero value otherwise.
func (o *CentralClusterNodeProfile) GetDefaultStorageSizeGi() int32 {
	if o == nil || IsNil(o.DefaultStorageSizeGi) {
		var ret int32
		return ret
	}
	return *o.DefaultStorageSizeGi
}

// GetDefaultStorageSizeGiOk returns a tuple with the DefaultStorageSizeGi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CentralClusterNodeProfile) GetDefaultStorageSizeGiOk() (*int32, bool) {
	if o == nil || IsNil(o.DefaultStorageSizeGi) {
		return nil, false
	}
	return o.DefaultStorageSizeGi, true
}

// HasDefaultStorageSizeGi returns a boolean if a field has been set.
func (o *CentralClusterNodeProfile) HasDefaultStorageSizeGi() bool {
	if o != nil && !IsNil(o.DefaultStorageSizeGi) {
		return true
	}

	return false
}

// SetDefaultStorageSizeGi gets a reference to the given int32 and assigns it to the DefaultStorageSizeGi field.
func (o *CentralClusterNodeProfile) SetDefaultStorageSizeGi(v int32) {
	o.DefaultStorageSizeGi = &v
}

// GetCpuNum returns the CpuNum field value if set, zero value otherwise.
func (o *CentralClusterNodeProfile) GetCpuNum() int32 {
	if o == nil || IsNil(o.CpuNum) {
		var ret int32
		return ret
	}
	return *o.CpuNum
}

// GetCpuNumOk returns a tuple with the CpuNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CentralClusterNodeProfile) GetCpuNumOk() (*int32, bool) {
	if o == nil || IsNil(o.CpuNum) {
		return nil, false
	}
	return o.CpuNum, true
}

// HasCpuNum returns a boolean if a field has been set.
func (o *CentralClusterNodeProfile) HasCpuNum() bool {
	if o != nil && !IsNil(o.CpuNum) {
		return true
	}

	return false
}

// SetCpuNum gets a reference to the given int32 and assigns it to the CpuNum field.
func (o *CentralClusterNodeProfile) SetCpuNum(v int32) {
	o.CpuNum = &v
}

// GetMemoryGi returns the MemoryGi field value if set, zero value otherwise.
func (o *CentralClusterNodeProfile) GetMemoryGi() int32 {
	if o == nil || IsNil(o.MemoryGi) {
		var ret int32
		return ret
	}
	return *o.MemoryGi
}

// GetMemoryGiOk returns a tuple with the MemoryGi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CentralClusterNodeProfile) GetMemoryGiOk() (*int32, bool) {
	if o == nil || IsNil(o.MemoryGi) {
		return nil, false
	}
	return o.MemoryGi, true
}

// HasMemoryGi returns a boolean if a field has been set.
func (o *CentralClusterNodeProfile) HasMemoryGi() bool {
	if o != nil && !IsNil(o.MemoryGi) {
		return true
	}

	return false
}

// SetMemoryGi gets a reference to the given int32 and assigns it to the MemoryGi field.
func (o *CentralClusterNodeProfile) SetMemoryGi(v int32) {
	o.MemoryGi = &v
}

func (o CentralClusterNodeProfile) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CentralClusterNodeProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	if !IsNil(o.DefaultNodeNum) {
		toSerialize["default_node_num"] = o.DefaultNodeNum
	}
	if !IsNil(o.MinStorageSizeGi) {
		toSerialize["min_storage_size_gi"] = o.MinStorageSizeGi
	}
	if !IsNil(o.MaxStorageSizeGi) {
		toSerialize["max_storage_size_gi"] = o.MaxStorageSizeGi
	}
	if !IsNil(o.DefaultStorageSizeGi) {
		toSerialize["default_storage_size_gi"] = o.DefaultStorageSizeGi
	}
	if !IsNil(o.CpuNum) {
		toSerialize["cpu_num"] = o.CpuNum
	}
	if !IsNil(o.MemoryGi) {
		toSerialize["memory_gi"] = o.MemoryGi
	}
	return toSerialize, nil
}

type NullableCentralClusterNodeProfile struct {
	value *CentralClusterNodeProfile
	isSet bool
}

func (v NullableCentralClusterNodeProfile) Get() *CentralClusterNodeProfile {
	return v.value
}

func (v *NullableCentralClusterNodeProfile) Set(val *CentralClusterNodeProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableCentralClusterNodeProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableCentralClusterNodeProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCentralClusterNodeProfile(val *CentralClusterNodeProfile) *NullableCentralClusterNodeProfile {
	return &NullableCentralClusterNodeProfile{value: val, isSet: true}
}

func (v NullableCentralClusterNodeProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCentralClusterNodeProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
