/*
gRPC for our DBaaS central service

notably uses gRPC-Gateway with OpenAPI

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package coreportalapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateProjectMaintenanceWindowRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateProjectMaintenanceWindowRequest{}

// UpdateProjectMaintenanceWindowRequest struct for UpdateProjectMaintenanceWindowRequest
type UpdateProjectMaintenanceWindowRequest struct {
	MaintenanceWindow CentralMaintenanceWindow `json:"maintenance_window"`
}

type _UpdateProjectMaintenanceWindowRequest UpdateProjectMaintenanceWindowRequest

// NewUpdateProjectMaintenanceWindowRequest instantiates a new UpdateProjectMaintenanceWindowRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProjectMaintenanceWindowRequest(maintenanceWindow CentralMaintenanceWindow) *UpdateProjectMaintenanceWindowRequest {
	this := UpdateProjectMaintenanceWindowRequest{}
	this.MaintenanceWindow = maintenanceWindow
	return &this
}

// NewUpdateProjectMaintenanceWindowRequestWithDefaults instantiates a new UpdateProjectMaintenanceWindowRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProjectMaintenanceWindowRequestWithDefaults() *UpdateProjectMaintenanceWindowRequest {
	this := UpdateProjectMaintenanceWindowRequest{}
	return &this
}

// GetMaintenanceWindow returns the MaintenanceWindow field value
func (o *UpdateProjectMaintenanceWindowRequest) GetMaintenanceWindow() CentralMaintenanceWindow {
	if o == nil {
		var ret CentralMaintenanceWindow
		return ret
	}

	return o.MaintenanceWindow
}

// GetMaintenanceWindowOk returns a tuple with the MaintenanceWindow field value
// and a boolean to check if the value has been set.
func (o *UpdateProjectMaintenanceWindowRequest) GetMaintenanceWindowOk() (*CentralMaintenanceWindow, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaintenanceWindow, true
}

// SetMaintenanceWindow sets field value
func (o *UpdateProjectMaintenanceWindowRequest) SetMaintenanceWindow(v CentralMaintenanceWindow) {
	o.MaintenanceWindow = v
}

func (o UpdateProjectMaintenanceWindowRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateProjectMaintenanceWindowRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["maintenance_window"] = o.MaintenanceWindow
	return toSerialize, nil
}

func (o *UpdateProjectMaintenanceWindowRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"maintenance_window",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateProjectMaintenanceWindowRequest := _UpdateProjectMaintenanceWindowRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateProjectMaintenanceWindowRequest)

	if err != nil {
		return err
	}

	*o = UpdateProjectMaintenanceWindowRequest(varUpdateProjectMaintenanceWindowRequest)

	return err
}

type NullableUpdateProjectMaintenanceWindowRequest struct {
	value *UpdateProjectMaintenanceWindowRequest
	isSet bool
}

func (v NullableUpdateProjectMaintenanceWindowRequest) Get() *UpdateProjectMaintenanceWindowRequest {
	return v.value
}

func (v *NullableUpdateProjectMaintenanceWindowRequest) Set(val *UpdateProjectMaintenanceWindowRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProjectMaintenanceWindowRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProjectMaintenanceWindowRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProjectMaintenanceWindowRequest(val *UpdateProjectMaintenanceWindowRequest) *NullableUpdateProjectMaintenanceWindowRequest {
	return &NullableUpdateProjectMaintenanceWindowRequest{value: val, isSet: true}
}

func (v NullableUpdateProjectMaintenanceWindowRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProjectMaintenanceWindowRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
