/*
gRPC for our DBaaS central service

notably uses gRPC-Gateway with OpenAPI

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package coreportalapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CentralCreatePrivateLinkEndpointResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CentralCreatePrivateLinkEndpointResp{}

// CentralCreatePrivateLinkEndpointResp struct for CentralCreatePrivateLinkEndpointResp
type CentralCreatePrivateLinkEndpointResp struct {
	PrivatelinkEndpoint CentralPrivateLinkEndpoint `json:"privatelink_endpoint"`
	BaseResp            CentralBaseResp            `json:"base_resp"`
}

type _CentralCreatePrivateLinkEndpointResp CentralCreatePrivateLinkEndpointResp

// NewCentralCreatePrivateLinkEndpointResp instantiates a new CentralCreatePrivateLinkEndpointResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCentralCreatePrivateLinkEndpointResp(privatelinkEndpoint CentralPrivateLinkEndpoint, baseResp CentralBaseResp) *CentralCreatePrivateLinkEndpointResp {
	this := CentralCreatePrivateLinkEndpointResp{}
	this.PrivatelinkEndpoint = privatelinkEndpoint
	this.BaseResp = baseResp
	return &this
}

// NewCentralCreatePrivateLinkEndpointRespWithDefaults instantiates a new CentralCreatePrivateLinkEndpointResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCentralCreatePrivateLinkEndpointRespWithDefaults() *CentralCreatePrivateLinkEndpointResp {
	this := CentralCreatePrivateLinkEndpointResp{}
	return &this
}

// GetPrivatelinkEndpoint returns the PrivatelinkEndpoint field value
func (o *CentralCreatePrivateLinkEndpointResp) GetPrivatelinkEndpoint() CentralPrivateLinkEndpoint {
	if o == nil {
		var ret CentralPrivateLinkEndpoint
		return ret
	}

	return o.PrivatelinkEndpoint
}

// GetPrivatelinkEndpointOk returns a tuple with the PrivatelinkEndpoint field value
// and a boolean to check if the value has been set.
func (o *CentralCreatePrivateLinkEndpointResp) GetPrivatelinkEndpointOk() (*CentralPrivateLinkEndpoint, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrivatelinkEndpoint, true
}

// SetPrivatelinkEndpoint sets field value
func (o *CentralCreatePrivateLinkEndpointResp) SetPrivatelinkEndpoint(v CentralPrivateLinkEndpoint) {
	o.PrivatelinkEndpoint = v
}

// GetBaseResp returns the BaseResp field value
func (o *CentralCreatePrivateLinkEndpointResp) GetBaseResp() CentralBaseResp {
	if o == nil {
		var ret CentralBaseResp
		return ret
	}

	return o.BaseResp
}

// GetBaseRespOk returns a tuple with the BaseResp field value
// and a boolean to check if the value has been set.
func (o *CentralCreatePrivateLinkEndpointResp) GetBaseRespOk() (*CentralBaseResp, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseResp, true
}

// SetBaseResp sets field value
func (o *CentralCreatePrivateLinkEndpointResp) SetBaseResp(v CentralBaseResp) {
	o.BaseResp = v
}

func (o CentralCreatePrivateLinkEndpointResp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CentralCreatePrivateLinkEndpointResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["privatelink_endpoint"] = o.PrivatelinkEndpoint
	toSerialize["base_resp"] = o.BaseResp
	return toSerialize, nil
}

func (o *CentralCreatePrivateLinkEndpointResp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"privatelink_endpoint",
		"base_resp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCentralCreatePrivateLinkEndpointResp := _CentralCreatePrivateLinkEndpointResp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCentralCreatePrivateLinkEndpointResp)

	if err != nil {
		return err
	}

	*o = CentralCreatePrivateLinkEndpointResp(varCentralCreatePrivateLinkEndpointResp)

	return err
}

type NullableCentralCreatePrivateLinkEndpointResp struct {
	value *CentralCreatePrivateLinkEndpointResp
	isSet bool
}

func (v NullableCentralCreatePrivateLinkEndpointResp) Get() *CentralCreatePrivateLinkEndpointResp {
	return v.value
}

func (v *NullableCentralCreatePrivateLinkEndpointResp) Set(val *CentralCreatePrivateLinkEndpointResp) {
	v.value = val
	v.isSet = true
}

func (v NullableCentralCreatePrivateLinkEndpointResp) IsSet() bool {
	return v.isSet
}

func (v *NullableCentralCreatePrivateLinkEndpointResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCentralCreatePrivateLinkEndpointResp(val *CentralCreatePrivateLinkEndpointResp) *NullableCentralCreatePrivateLinkEndpointResp {
	return &NullableCentralCreatePrivateLinkEndpointResp{value: val, isSet: true}
}

func (v NullableCentralCreatePrivateLinkEndpointResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCentralCreatePrivateLinkEndpointResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
