/*
gRPC for our DBaaS central service

notably uses gRPC-Gateway with OpenAPI

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package coreportalapi

import (
	"encoding/json"
)

// checks if the CentralGetProjectRegionCIDRResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CentralGetProjectRegionCIDRResp{}

// CentralGetProjectRegionCIDRResp struct for CentralGetProjectRegionCIDRResp
type CentralGetProjectRegionCIDRResp struct {
	ProjectRegionCidrs []CentralProjectRegionCIDR `json:"project_region_cidrs,omitempty"`
	BaseResp           *CentralBaseResp           `json:"base_resp,omitempty"`
}

// NewCentralGetProjectRegionCIDRResp instantiates a new CentralGetProjectRegionCIDRResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCentralGetProjectRegionCIDRResp() *CentralGetProjectRegionCIDRResp {
	this := CentralGetProjectRegionCIDRResp{}
	return &this
}

// NewCentralGetProjectRegionCIDRRespWithDefaults instantiates a new CentralGetProjectRegionCIDRResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCentralGetProjectRegionCIDRRespWithDefaults() *CentralGetProjectRegionCIDRResp {
	this := CentralGetProjectRegionCIDRResp{}
	return &this
}

// GetProjectRegionCidrs returns the ProjectRegionCidrs field value if set, zero value otherwise.
func (o *CentralGetProjectRegionCIDRResp) GetProjectRegionCidrs() []CentralProjectRegionCIDR {
	if o == nil || IsNil(o.ProjectRegionCidrs) {
		var ret []CentralProjectRegionCIDR
		return ret
	}
	return o.ProjectRegionCidrs
}

// GetProjectRegionCidrsOk returns a tuple with the ProjectRegionCidrs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CentralGetProjectRegionCIDRResp) GetProjectRegionCidrsOk() ([]CentralProjectRegionCIDR, bool) {
	if o == nil || IsNil(o.ProjectRegionCidrs) {
		return nil, false
	}
	return o.ProjectRegionCidrs, true
}

// HasProjectRegionCidrs returns a boolean if a field has been set.
func (o *CentralGetProjectRegionCIDRResp) HasProjectRegionCidrs() bool {
	if o != nil && !IsNil(o.ProjectRegionCidrs) {
		return true
	}

	return false
}

// SetProjectRegionCidrs gets a reference to the given []CentralProjectRegionCIDR and assigns it to the ProjectRegionCidrs field.
func (o *CentralGetProjectRegionCIDRResp) SetProjectRegionCidrs(v []CentralProjectRegionCIDR) {
	o.ProjectRegionCidrs = v
}

// GetBaseResp returns the BaseResp field value if set, zero value otherwise.
func (o *CentralGetProjectRegionCIDRResp) GetBaseResp() CentralBaseResp {
	if o == nil || IsNil(o.BaseResp) {
		var ret CentralBaseResp
		return ret
	}
	return *o.BaseResp
}

// GetBaseRespOk returns a tuple with the BaseResp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CentralGetProjectRegionCIDRResp) GetBaseRespOk() (*CentralBaseResp, bool) {
	if o == nil || IsNil(o.BaseResp) {
		return nil, false
	}
	return o.BaseResp, true
}

// HasBaseResp returns a boolean if a field has been set.
func (o *CentralGetProjectRegionCIDRResp) HasBaseResp() bool {
	if o != nil && !IsNil(o.BaseResp) {
		return true
	}

	return false
}

// SetBaseResp gets a reference to the given CentralBaseResp and assigns it to the BaseResp field.
func (o *CentralGetProjectRegionCIDRResp) SetBaseResp(v CentralBaseResp) {
	o.BaseResp = &v
}

func (o CentralGetProjectRegionCIDRResp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CentralGetProjectRegionCIDRResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjectRegionCidrs) {
		toSerialize["project_region_cidrs"] = o.ProjectRegionCidrs
	}
	if !IsNil(o.BaseResp) {
		toSerialize["base_resp"] = o.BaseResp
	}
	return toSerialize, nil
}

type NullableCentralGetProjectRegionCIDRResp struct {
	value *CentralGetProjectRegionCIDRResp
	isSet bool
}

func (v NullableCentralGetProjectRegionCIDRResp) Get() *CentralGetProjectRegionCIDRResp {
	return v.value
}

func (v *NullableCentralGetProjectRegionCIDRResp) Set(val *CentralGetProjectRegionCIDRResp) {
	v.value = val
	v.isSet = true
}

func (v NullableCentralGetProjectRegionCIDRResp) IsSet() bool {
	return v.isSet
}

func (v *NullableCentralGetProjectRegionCIDRResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCentralGetProjectRegionCIDRResp(val *CentralGetProjectRegionCIDRResp) *NullableCentralGetProjectRegionCIDRResp {
	return &NullableCentralGetProjectRegionCIDRResp{value: val, isSet: true}
}

func (v NullableCentralGetProjectRegionCIDRResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCentralGetProjectRegionCIDRResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
