/*
gRPC for our DBaaS central service

notably uses gRPC-Gateway with OpenAPI

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package coreportalapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CentralCloudProvider type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CentralCloudProvider{}

// CentralCloudProvider struct for CentralCloudProvider
type CentralCloudProvider struct {
	Name    string          `json:"name"`
	Regions []CentralRegion `json:"regions"`
}

type _CentralCloudProvider CentralCloudProvider

// NewCentralCloudProvider instantiates a new CentralCloudProvider object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCentralCloudProvider(name string, regions []CentralRegion) *CentralCloudProvider {
	this := CentralCloudProvider{}
	this.Name = name
	this.Regions = regions
	return &this
}

// NewCentralCloudProviderWithDefaults instantiates a new CentralCloudProvider object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCentralCloudProviderWithDefaults() *CentralCloudProvider {
	this := CentralCloudProvider{}
	return &this
}

// GetName returns the Name field value
func (o *CentralCloudProvider) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CentralCloudProvider) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CentralCloudProvider) SetName(v string) {
	o.Name = v
}

// GetRegions returns the Regions field value
func (o *CentralCloudProvider) GetRegions() []CentralRegion {
	if o == nil {
		var ret []CentralRegion
		return ret
	}

	return o.Regions
}

// GetRegionsOk returns a tuple with the Regions field value
// and a boolean to check if the value has been set.
func (o *CentralCloudProvider) GetRegionsOk() ([]CentralRegion, bool) {
	if o == nil {
		return nil, false
	}
	return o.Regions, true
}

// SetRegions sets field value
func (o *CentralCloudProvider) SetRegions(v []CentralRegion) {
	o.Regions = v
}

func (o CentralCloudProvider) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CentralCloudProvider) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["regions"] = o.Regions
	return toSerialize, nil
}

func (o *CentralCloudProvider) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"regions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCentralCloudProvider := _CentralCloudProvider{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCentralCloudProvider)

	if err != nil {
		return err
	}

	*o = CentralCloudProvider(varCentralCloudProvider)

	return err
}

type NullableCentralCloudProvider struct {
	value *CentralCloudProvider
	isSet bool
}

func (v NullableCentralCloudProvider) Get() *CentralCloudProvider {
	return v.value
}

func (v *NullableCentralCloudProvider) Set(val *CentralCloudProvider) {
	v.value = val
	v.isSet = true
}

func (v NullableCentralCloudProvider) IsSet() bool {
	return v.isSet
}

func (v *NullableCentralCloudProvider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCentralCloudProvider(val *CentralCloudProvider) *NullableCentralCloudProvider {
	return &NullableCentralCloudProvider{value: val, isSet: true}
}

func (v NullableCentralCloudProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCentralCloudProvider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
