/*
gRPC for our DBaaS central service

notably uses gRPC-Gateway with OpenAPI

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package coreportalapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CentralListPrivateLinkEndpointsOfProjectResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CentralListPrivateLinkEndpointsOfProjectResp{}

// CentralListPrivateLinkEndpointsOfProjectResp struct for CentralListPrivateLinkEndpointsOfProjectResp
type CentralListPrivateLinkEndpointsOfProjectResp struct {
	Endpoints []CentralPrivateLinkEndpoint `json:"endpoints"`
	BaseResp  CentralBaseResp              `json:"base_resp"`
}

type _CentralListPrivateLinkEndpointsOfProjectResp CentralListPrivateLinkEndpointsOfProjectResp

// NewCentralListPrivateLinkEndpointsOfProjectResp instantiates a new CentralListPrivateLinkEndpointsOfProjectResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCentralListPrivateLinkEndpointsOfProjectResp(endpoints []CentralPrivateLinkEndpoint, baseResp CentralBaseResp) *CentralListPrivateLinkEndpointsOfProjectResp {
	this := CentralListPrivateLinkEndpointsOfProjectResp{}
	this.Endpoints = endpoints
	this.BaseResp = baseResp
	return &this
}

// NewCentralListPrivateLinkEndpointsOfProjectRespWithDefaults instantiates a new CentralListPrivateLinkEndpointsOfProjectResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCentralListPrivateLinkEndpointsOfProjectRespWithDefaults() *CentralListPrivateLinkEndpointsOfProjectResp {
	this := CentralListPrivateLinkEndpointsOfProjectResp{}
	return &this
}

// GetEndpoints returns the Endpoints field value
func (o *CentralListPrivateLinkEndpointsOfProjectResp) GetEndpoints() []CentralPrivateLinkEndpoint {
	if o == nil {
		var ret []CentralPrivateLinkEndpoint
		return ret
	}

	return o.Endpoints
}

// GetEndpointsOk returns a tuple with the Endpoints field value
// and a boolean to check if the value has been set.
func (o *CentralListPrivateLinkEndpointsOfProjectResp) GetEndpointsOk() ([]CentralPrivateLinkEndpoint, bool) {
	if o == nil {
		return nil, false
	}
	return o.Endpoints, true
}

// SetEndpoints sets field value
func (o *CentralListPrivateLinkEndpointsOfProjectResp) SetEndpoints(v []CentralPrivateLinkEndpoint) {
	o.Endpoints = v
}

// GetBaseResp returns the BaseResp field value
func (o *CentralListPrivateLinkEndpointsOfProjectResp) GetBaseResp() CentralBaseResp {
	if o == nil {
		var ret CentralBaseResp
		return ret
	}

	return o.BaseResp
}

// GetBaseRespOk returns a tuple with the BaseResp field value
// and a boolean to check if the value has been set.
func (o *CentralListPrivateLinkEndpointsOfProjectResp) GetBaseRespOk() (*CentralBaseResp, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseResp, true
}

// SetBaseResp sets field value
func (o *CentralListPrivateLinkEndpointsOfProjectResp) SetBaseResp(v CentralBaseResp) {
	o.BaseResp = v
}

func (o CentralListPrivateLinkEndpointsOfProjectResp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CentralListPrivateLinkEndpointsOfProjectResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["endpoints"] = o.Endpoints
	toSerialize["base_resp"] = o.BaseResp
	return toSerialize, nil
}

func (o *CentralListPrivateLinkEndpointsOfProjectResp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"endpoints",
		"base_resp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCentralListPrivateLinkEndpointsOfProjectResp := _CentralListPrivateLinkEndpointsOfProjectResp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCentralListPrivateLinkEndpointsOfProjectResp)

	if err != nil {
		return err
	}

	*o = CentralListPrivateLinkEndpointsOfProjectResp(varCentralListPrivateLinkEndpointsOfProjectResp)

	return err
}

type NullableCentralListPrivateLinkEndpointsOfProjectResp struct {
	value *CentralListPrivateLinkEndpointsOfProjectResp
	isSet bool
}

func (v NullableCentralListPrivateLinkEndpointsOfProjectResp) Get() *CentralListPrivateLinkEndpointsOfProjectResp {
	return v.value
}

func (v *NullableCentralListPrivateLinkEndpointsOfProjectResp) Set(val *CentralListPrivateLinkEndpointsOfProjectResp) {
	v.value = val
	v.isSet = true
}

func (v NullableCentralListPrivateLinkEndpointsOfProjectResp) IsSet() bool {
	return v.isSet
}

func (v *NullableCentralListPrivateLinkEndpointsOfProjectResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCentralListPrivateLinkEndpointsOfProjectResp(val *CentralListPrivateLinkEndpointsOfProjectResp) *NullableCentralListPrivateLinkEndpointsOfProjectResp {
	return &NullableCentralListPrivateLinkEndpointsOfProjectResp{value: val, isSet: true}
}

func (v NullableCentralListPrivateLinkEndpointsOfProjectResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCentralListPrivateLinkEndpointsOfProjectResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
