/*
gRPC for our DBaaS central service

notably uses gRPC-Gateway with OpenAPI

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package coreportalapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CentralTiKVNodes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CentralTiKVNodes{}

// CentralTiKVNodes struct for CentralTiKVNodes
type CentralTiKVNodes struct {
	Total int32             `json:"total"`
	Items []CentralTiKVNode `json:"items"`
}

type _CentralTiKVNodes CentralTiKVNodes

// NewCentralTiKVNodes instantiates a new CentralTiKVNodes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCentralTiKVNodes(total int32, items []CentralTiKVNode) *CentralTiKVNodes {
	this := CentralTiKVNodes{}
	this.Total = total
	this.Items = items
	return &this
}

// NewCentralTiKVNodesWithDefaults instantiates a new CentralTiKVNodes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCentralTiKVNodesWithDefaults() *CentralTiKVNodes {
	this := CentralTiKVNodes{}
	return &this
}

// GetTotal returns the Total field value
func (o *CentralTiKVNodes) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *CentralTiKVNodes) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *CentralTiKVNodes) SetTotal(v int32) {
	o.Total = v
}

// GetItems returns the Items field value
func (o *CentralTiKVNodes) GetItems() []CentralTiKVNode {
	if o == nil {
		var ret []CentralTiKVNode
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *CentralTiKVNodes) GetItemsOk() ([]CentralTiKVNode, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *CentralTiKVNodes) SetItems(v []CentralTiKVNode) {
	o.Items = v
}

func (o CentralTiKVNodes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CentralTiKVNodes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *CentralTiKVNodes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total",
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCentralTiKVNodes := _CentralTiKVNodes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCentralTiKVNodes)

	if err != nil {
		return err
	}

	*o = CentralTiKVNodes(varCentralTiKVNodes)

	return err
}

type NullableCentralTiKVNodes struct {
	value *CentralTiKVNodes
	isSet bool
}

func (v NullableCentralTiKVNodes) Get() *CentralTiKVNodes {
	return v.value
}

func (v *NullableCentralTiKVNodes) Set(val *CentralTiKVNodes) {
	v.value = val
	v.isSet = true
}

func (v NullableCentralTiKVNodes) IsSet() bool {
	return v.isSet
}

func (v *NullableCentralTiKVNodes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCentralTiKVNodes(val *CentralTiKVNodes) *NullableCentralTiKVNodes {
	return &NullableCentralTiKVNodes{value: val, isSet: true}
}

func (v NullableCentralTiKVNodes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCentralTiKVNodes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
