/*
gRPC for our DBaaS central service

notably uses gRPC-Gateway with OpenAPI

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package coreportalapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CentralGetTiDBCloudDelegationInfoResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CentralGetTiDBCloudDelegationInfoResp{}

// CentralGetTiDBCloudDelegationInfoResp struct for CentralGetTiDBCloudDelegationInfoResp
type CentralGetTiDBCloudDelegationInfoResp struct {
	AccountId  string          `json:"account_id"`
	ExternalId string          `json:"external_id"`
	BaseResp   CentralBaseResp `json:"base_resp"`
}

type _CentralGetTiDBCloudDelegationInfoResp CentralGetTiDBCloudDelegationInfoResp

// NewCentralGetTiDBCloudDelegationInfoResp instantiates a new CentralGetTiDBCloudDelegationInfoResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCentralGetTiDBCloudDelegationInfoResp(accountId string, externalId string, baseResp CentralBaseResp) *CentralGetTiDBCloudDelegationInfoResp {
	this := CentralGetTiDBCloudDelegationInfoResp{}
	this.AccountId = accountId
	this.ExternalId = externalId
	this.BaseResp = baseResp
	return &this
}

// NewCentralGetTiDBCloudDelegationInfoRespWithDefaults instantiates a new CentralGetTiDBCloudDelegationInfoResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCentralGetTiDBCloudDelegationInfoRespWithDefaults() *CentralGetTiDBCloudDelegationInfoResp {
	this := CentralGetTiDBCloudDelegationInfoResp{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *CentralGetTiDBCloudDelegationInfoResp) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *CentralGetTiDBCloudDelegationInfoResp) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *CentralGetTiDBCloudDelegationInfoResp) SetAccountId(v string) {
	o.AccountId = v
}

// GetExternalId returns the ExternalId field value
func (o *CentralGetTiDBCloudDelegationInfoResp) GetExternalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value
// and a boolean to check if the value has been set.
func (o *CentralGetTiDBCloudDelegationInfoResp) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalId, true
}

// SetExternalId sets field value
func (o *CentralGetTiDBCloudDelegationInfoResp) SetExternalId(v string) {
	o.ExternalId = v
}

// GetBaseResp returns the BaseResp field value
func (o *CentralGetTiDBCloudDelegationInfoResp) GetBaseResp() CentralBaseResp {
	if o == nil {
		var ret CentralBaseResp
		return ret
	}

	return o.BaseResp
}

// GetBaseRespOk returns a tuple with the BaseResp field value
// and a boolean to check if the value has been set.
func (o *CentralGetTiDBCloudDelegationInfoResp) GetBaseRespOk() (*CentralBaseResp, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseResp, true
}

// SetBaseResp sets field value
func (o *CentralGetTiDBCloudDelegationInfoResp) SetBaseResp(v CentralBaseResp) {
	o.BaseResp = v
}

func (o CentralGetTiDBCloudDelegationInfoResp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CentralGetTiDBCloudDelegationInfoResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_id"] = o.AccountId
	toSerialize["external_id"] = o.ExternalId
	toSerialize["base_resp"] = o.BaseResp
	return toSerialize, nil
}

func (o *CentralGetTiDBCloudDelegationInfoResp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_id",
		"external_id",
		"base_resp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCentralGetTiDBCloudDelegationInfoResp := _CentralGetTiDBCloudDelegationInfoResp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCentralGetTiDBCloudDelegationInfoResp)

	if err != nil {
		return err
	}

	*o = CentralGetTiDBCloudDelegationInfoResp(varCentralGetTiDBCloudDelegationInfoResp)

	return err
}

type NullableCentralGetTiDBCloudDelegationInfoResp struct {
	value *CentralGetTiDBCloudDelegationInfoResp
	isSet bool
}

func (v NullableCentralGetTiDBCloudDelegationInfoResp) Get() *CentralGetTiDBCloudDelegationInfoResp {
	return v.value
}

func (v *NullableCentralGetTiDBCloudDelegationInfoResp) Set(val *CentralGetTiDBCloudDelegationInfoResp) {
	v.value = val
	v.isSet = true
}

func (v NullableCentralGetTiDBCloudDelegationInfoResp) IsSet() bool {
	return v.isSet
}

func (v *NullableCentralGetTiDBCloudDelegationInfoResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCentralGetTiDBCloudDelegationInfoResp(val *CentralGetTiDBCloudDelegationInfoResp) *NullableCentralGetTiDBCloudDelegationInfoResp {
	return &NullableCentralGetTiDBCloudDelegationInfoResp{value: val, isSet: true}
}

func (v NullableCentralGetTiDBCloudDelegationInfoResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCentralGetTiDBCloudDelegationInfoResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
