ap-northeast-1:
  - name: ap-northeast-1
    cluster_id: 10959546687428216535
    host: gateway01.ap-northeast-1.prod.aws.tidbcloud.com
    user: 3L7skcinRJz38TD.root
    plan: starter
    tidb_pool: vip-tidb-pool
  - name: ap-northeast-1
    cluster_id: 10959546687428216535
    host: gateway01.ap-northeast-1.prod.aws.tidbcloud.com
    user: 3L7skcinRJz38TD.root
    plan: essential
    tidb_pool: vip-tidb-pool
us-west-2:
  - name: ap-northeast-1
    cluster_id: 10959546687428216535
    host: gateway01.ap-northeast-1.prod.aws.tidbcloud.com
    user: 3L7skcinRJz38TD.root
    plan: essential
    tidb_pool: vip-tidb-pool