/*
Import APIs for TiDB Cloud Serverless

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package consoleimportapi

import (
	"encoding/json"
)

// checks if the ListTargetTablesResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListTargetTablesResp{}

// ListTargetTablesResp struct for ListTargetTablesResp
type ListTargetTablesResp struct {
	// The list of tables.
	Databases []Database `json:"databases,omitempty"`
	BaseResp  *BaseResp  `json:"base_resp,omitempty"`
}

// NewListTargetTablesResp instantiates a new ListTargetTablesResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTargetTablesResp() *ListTargetTablesResp {
	this := ListTargetTablesResp{}
	return &this
}

// NewListTargetTablesRespWithDefaults instantiates a new ListTargetTablesResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTargetTablesRespWithDefaults() *ListTargetTablesResp {
	this := ListTargetTablesResp{}
	return &this
}

// GetDatabases returns the Databases field value if set, zero value otherwise.
func (o *ListTargetTablesResp) GetDatabases() []Database {
	if o == nil || IsNil(o.Databases) {
		var ret []Database
		return ret
	}
	return o.Databases
}

// GetDatabasesOk returns a tuple with the Databases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListTargetTablesResp) GetDatabasesOk() ([]Database, bool) {
	if o == nil || IsNil(o.Databases) {
		return nil, false
	}
	return o.Databases, true
}

// HasDatabases returns a boolean if a field has been set.
func (o *ListTargetTablesResp) HasDatabases() bool {
	if o != nil && !IsNil(o.Databases) {
		return true
	}

	return false
}

// SetDatabases gets a reference to the given []Database and assigns it to the Databases field.
func (o *ListTargetTablesResp) SetDatabases(v []Database) {
	o.Databases = v
}

// GetBaseResp returns the BaseResp field value if set, zero value otherwise.
func (o *ListTargetTablesResp) GetBaseResp() BaseResp {
	if o == nil || IsNil(o.BaseResp) {
		var ret BaseResp
		return ret
	}
	return *o.BaseResp
}

// GetBaseRespOk returns a tuple with the BaseResp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListTargetTablesResp) GetBaseRespOk() (*BaseResp, bool) {
	if o == nil || IsNil(o.BaseResp) {
		return nil, false
	}
	return o.BaseResp, true
}

// HasBaseResp returns a boolean if a field has been set.
func (o *ListTargetTablesResp) HasBaseResp() bool {
	if o != nil && !IsNil(o.BaseResp) {
		return true
	}

	return false
}

// SetBaseResp gets a reference to the given BaseResp and assigns it to the BaseResp field.
func (o *ListTargetTablesResp) SetBaseResp(v BaseResp) {
	o.BaseResp = &v
}

func (o ListTargetTablesResp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListTargetTablesResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Databases) {
		toSerialize["databases"] = o.Databases
	}
	if !IsNil(o.BaseResp) {
		toSerialize["base_resp"] = o.BaseResp
	}
	return toSerialize, nil
}

type NullableListTargetTablesResp struct {
	value *ListTargetTablesResp
	isSet bool
}

func (v NullableListTargetTablesResp) Get() *ListTargetTablesResp {
	return v.value
}

func (v *NullableListTargetTablesResp) Set(val *ListTargetTablesResp) {
	v.value = val
	v.isSet = true
}

func (v NullableListTargetTablesResp) IsSet() bool {
	return v.isSet
}

func (v *NullableListTargetTablesResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTargetTablesResp(val *ListTargetTablesResp) *NullableListTargetTablesResp {
	return &NullableListTargetTablesResp{value: val, isSet: true}
}

func (v NullableListTargetTablesResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTargetTablesResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
