/*
Import APIs for TiDB Cloud Serverless

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package consoleimportapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the S3Source type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &S3Source{}

// S3Source struct for S3Source
type S3Source struct {
	// The S3 URI of the import source.
	Uri       string               `json:"uri"`
	AuthType  ImportS3AuthTypeEnum `json:"auth_type"`
	RoleArn   *string              `json:"role_arn,omitempty"`
	AccessKey *S3SourceAccessKey   `json:"access_key,omitempty"`
	// The target table information of the import.
	TargetTableInfos []ImportTargetTableInfo `json:"target_table_infos,omitempty"`
}

type _S3Source S3Source

// NewS3Source instantiates a new S3Source object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewS3Source(uri string, authType ImportS3AuthTypeEnum) *S3Source {
	this := S3Source{}
	this.Uri = uri
	this.AuthType = authType
	return &this
}

// NewS3SourceWithDefaults instantiates a new S3Source object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewS3SourceWithDefaults() *S3Source {
	this := S3Source{}
	return &this
}

// GetUri returns the Uri field value
func (o *S3Source) GetUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uri
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *S3Source) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uri, true
}

// SetUri sets field value
func (o *S3Source) SetUri(v string) {
	o.Uri = v
}

// GetAuthType returns the AuthType field value
func (o *S3Source) GetAuthType() ImportS3AuthTypeEnum {
	if o == nil {
		var ret ImportS3AuthTypeEnum
		return ret
	}

	return o.AuthType
}

// GetAuthTypeOk returns a tuple with the AuthType field value
// and a boolean to check if the value has been set.
func (o *S3Source) GetAuthTypeOk() (*ImportS3AuthTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthType, true
}

// SetAuthType sets field value
func (o *S3Source) SetAuthType(v ImportS3AuthTypeEnum) {
	o.AuthType = v
}

// GetRoleArn returns the RoleArn field value if set, zero value otherwise.
func (o *S3Source) GetRoleArn() string {
	if o == nil || IsNil(o.RoleArn) {
		var ret string
		return ret
	}
	return *o.RoleArn
}

// GetRoleArnOk returns a tuple with the RoleArn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3Source) GetRoleArnOk() (*string, bool) {
	if o == nil || IsNil(o.RoleArn) {
		return nil, false
	}
	return o.RoleArn, true
}

// HasRoleArn returns a boolean if a field has been set.
func (o *S3Source) HasRoleArn() bool {
	if o != nil && !IsNil(o.RoleArn) {
		return true
	}

	return false
}

// SetRoleArn gets a reference to the given string and assigns it to the RoleArn field.
func (o *S3Source) SetRoleArn(v string) {
	o.RoleArn = &v
}

// GetAccessKey returns the AccessKey field value if set, zero value otherwise.
func (o *S3Source) GetAccessKey() S3SourceAccessKey {
	if o == nil || IsNil(o.AccessKey) {
		var ret S3SourceAccessKey
		return ret
	}
	return *o.AccessKey
}

// GetAccessKeyOk returns a tuple with the AccessKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3Source) GetAccessKeyOk() (*S3SourceAccessKey, bool) {
	if o == nil || IsNil(o.AccessKey) {
		return nil, false
	}
	return o.AccessKey, true
}

// HasAccessKey returns a boolean if a field has been set.
func (o *S3Source) HasAccessKey() bool {
	if o != nil && !IsNil(o.AccessKey) {
		return true
	}

	return false
}

// SetAccessKey gets a reference to the given S3SourceAccessKey and assigns it to the AccessKey field.
func (o *S3Source) SetAccessKey(v S3SourceAccessKey) {
	o.AccessKey = &v
}

// GetTargetTableInfos returns the TargetTableInfos field value if set, zero value otherwise.
func (o *S3Source) GetTargetTableInfos() []ImportTargetTableInfo {
	if o == nil || IsNil(o.TargetTableInfos) {
		var ret []ImportTargetTableInfo
		return ret
	}
	return o.TargetTableInfos
}

// GetTargetTableInfosOk returns a tuple with the TargetTableInfos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3Source) GetTargetTableInfosOk() ([]ImportTargetTableInfo, bool) {
	if o == nil || IsNil(o.TargetTableInfos) {
		return nil, false
	}
	return o.TargetTableInfos, true
}

// HasTargetTableInfos returns a boolean if a field has been set.
func (o *S3Source) HasTargetTableInfos() bool {
	if o != nil && !IsNil(o.TargetTableInfos) {
		return true
	}

	return false
}

// SetTargetTableInfos gets a reference to the given []ImportTargetTableInfo and assigns it to the TargetTableInfos field.
func (o *S3Source) SetTargetTableInfos(v []ImportTargetTableInfo) {
	o.TargetTableInfos = v
}

func (o S3Source) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o S3Source) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uri"] = o.Uri
	toSerialize["auth_type"] = o.AuthType
	if !IsNil(o.RoleArn) {
		toSerialize["role_arn"] = o.RoleArn
	}
	if !IsNil(o.AccessKey) {
		toSerialize["access_key"] = o.AccessKey
	}
	if !IsNil(o.TargetTableInfos) {
		toSerialize["target_table_infos"] = o.TargetTableInfos
	}
	return toSerialize, nil
}

func (o *S3Source) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uri",
		"auth_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varS3Source := _S3Source{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varS3Source)

	if err != nil {
		return err
	}

	*o = S3Source(varS3Source)

	return err
}

type NullableS3Source struct {
	value *S3Source
	isSet bool
}

func (v NullableS3Source) Get() *S3Source {
	return v.value
}

func (v *NullableS3Source) Set(val *S3Source) {
	v.value = val
	v.isSet = true
}

func (v NullableS3Source) IsSet() bool {
	return v.isSet
}

func (v *NullableS3Source) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableS3Source(val *S3Source) *NullableS3Source {
	return &NullableS3Source{value: val, isSet: true}
}

func (v NullableS3Source) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableS3Source) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
