/*
Import APIs for TiDB Cloud Serverless

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package consoleimportapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OSSSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OSSSource{}

// OSSSource struct for OSSSource
type OSSSource struct {
	// The OSS URI of the import source.
	Uri       string                `json:"uri"`
	AuthType  ImportOSSAuthTypeEnum `json:"auth_type"`
	AccessKey *OSSSourceAccessKey   `json:"access_key,omitempty"`
	RoleArn   *string               `json:"role_arn,omitempty"`
	// The target table information of the import.
	TargetTableInfos []ImportTargetTableInfo `json:"target_table_infos,omitempty"`
}

type _OSSSource OSSSource

// NewOSSSource instantiates a new OSSSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOSSSource(uri string, authType ImportOSSAuthTypeEnum) *OSSSource {
	this := OSSSource{}
	this.Uri = uri
	this.AuthType = authType
	return &this
}

// NewOSSSourceWithDefaults instantiates a new OSSSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOSSSourceWithDefaults() *OSSSource {
	this := OSSSource{}
	return &this
}

// GetUri returns the Uri field value
func (o *OSSSource) GetUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uri
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *OSSSource) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uri, true
}

// SetUri sets field value
func (o *OSSSource) SetUri(v string) {
	o.Uri = v
}

// GetAuthType returns the AuthType field value
func (o *OSSSource) GetAuthType() ImportOSSAuthTypeEnum {
	if o == nil {
		var ret ImportOSSAuthTypeEnum
		return ret
	}

	return o.AuthType
}

// GetAuthTypeOk returns a tuple with the AuthType field value
// and a boolean to check if the value has been set.
func (o *OSSSource) GetAuthTypeOk() (*ImportOSSAuthTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthType, true
}

// SetAuthType sets field value
func (o *OSSSource) SetAuthType(v ImportOSSAuthTypeEnum) {
	o.AuthType = v
}

// GetAccessKey returns the AccessKey field value if set, zero value otherwise.
func (o *OSSSource) GetAccessKey() OSSSourceAccessKey {
	if o == nil || IsNil(o.AccessKey) {
		var ret OSSSourceAccessKey
		return ret
	}
	return *o.AccessKey
}

// GetAccessKeyOk returns a tuple with the AccessKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OSSSource) GetAccessKeyOk() (*OSSSourceAccessKey, bool) {
	if o == nil || IsNil(o.AccessKey) {
		return nil, false
	}
	return o.AccessKey, true
}

// HasAccessKey returns a boolean if a field has been set.
func (o *OSSSource) HasAccessKey() bool {
	if o != nil && !IsNil(o.AccessKey) {
		return true
	}

	return false
}

// SetAccessKey gets a reference to the given OSSSourceAccessKey and assigns it to the AccessKey field.
func (o *OSSSource) SetAccessKey(v OSSSourceAccessKey) {
	o.AccessKey = &v
}

// GetRoleArn returns the RoleArn field value if set, zero value otherwise.
func (o *OSSSource) GetRoleArn() string {
	if o == nil || IsNil(o.RoleArn) {
		var ret string
		return ret
	}
	return *o.RoleArn
}

// GetRoleArnOk returns a tuple with the RoleArn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OSSSource) GetRoleArnOk() (*string, bool) {
	if o == nil || IsNil(o.RoleArn) {
		return nil, false
	}
	return o.RoleArn, true
}

// HasRoleArn returns a boolean if a field has been set.
func (o *OSSSource) HasRoleArn() bool {
	if o != nil && !IsNil(o.RoleArn) {
		return true
	}

	return false
}

// SetRoleArn gets a reference to the given string and assigns it to the RoleArn field.
func (o *OSSSource) SetRoleArn(v string) {
	o.RoleArn = &v
}

// GetTargetTableInfos returns the TargetTableInfos field value if set, zero value otherwise.
func (o *OSSSource) GetTargetTableInfos() []ImportTargetTableInfo {
	if o == nil || IsNil(o.TargetTableInfos) {
		var ret []ImportTargetTableInfo
		return ret
	}
	return o.TargetTableInfos
}

// GetTargetTableInfosOk returns a tuple with the TargetTableInfos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OSSSource) GetTargetTableInfosOk() ([]ImportTargetTableInfo, bool) {
	if o == nil || IsNil(o.TargetTableInfos) {
		return nil, false
	}
	return o.TargetTableInfos, true
}

// HasTargetTableInfos returns a boolean if a field has been set.
func (o *OSSSource) HasTargetTableInfos() bool {
	if o != nil && !IsNil(o.TargetTableInfos) {
		return true
	}

	return false
}

// SetTargetTableInfos gets a reference to the given []ImportTargetTableInfo and assigns it to the TargetTableInfos field.
func (o *OSSSource) SetTargetTableInfos(v []ImportTargetTableInfo) {
	o.TargetTableInfos = v
}

func (o OSSSource) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OSSSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uri"] = o.Uri
	toSerialize["auth_type"] = o.AuthType
	if !IsNil(o.AccessKey) {
		toSerialize["access_key"] = o.AccessKey
	}
	if !IsNil(o.RoleArn) {
		toSerialize["role_arn"] = o.RoleArn
	}
	if !IsNil(o.TargetTableInfos) {
		toSerialize["target_table_infos"] = o.TargetTableInfos
	}
	return toSerialize, nil
}

func (o *OSSSource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uri",
		"auth_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOSSSource := _OSSSource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOSSSource)

	if err != nil {
		return err
	}

	*o = OSSSource(varOSSSource)

	return err
}

type NullableOSSSource struct {
	value *OSSSource
	isSet bool
}

func (v NullableOSSSource) Get() *OSSSource {
	return v.value
}

func (v *NullableOSSSource) Set(val *OSSSource) {
	v.value = val
	v.isSet = true
}

func (v NullableOSSSource) IsSet() bool {
	return v.isSet
}

func (v *NullableOSSSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOSSSource(val *OSSSource) *NullableOSSSource {
	return &NullableOSSSource{value: val, isSet: true}
}

func (v NullableOSSSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOSSSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
