/*
Import APIs for TiDB Cloud Serverless

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package consoleimportapi

import (
	"encoding/json"
)

// checks if the ImportsSearchImportFilesResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImportsSearchImportFilesResp{}

// ImportsSearchImportFilesResp struct for ImportsSearchImportFilesResp
type ImportsSearchImportFilesResp struct {
	// The list of tables which has matched data files.
	TargetTables []TableMatch `json:"target_tables,omitempty"`
	// The warning message consists of the unmatched tables.
	WarningMessage *string   `json:"warning_message,omitempty"`
	BaseResp       *BaseResp `json:"base_resp,omitempty"`
}

// NewImportsSearchImportFilesResp instantiates a new ImportsSearchImportFilesResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImportsSearchImportFilesResp() *ImportsSearchImportFilesResp {
	this := ImportsSearchImportFilesResp{}
	return &this
}

// NewImportsSearchImportFilesRespWithDefaults instantiates a new ImportsSearchImportFilesResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImportsSearchImportFilesRespWithDefaults() *ImportsSearchImportFilesResp {
	this := ImportsSearchImportFilesResp{}
	return &this
}

// GetTargetTables returns the TargetTables field value if set, zero value otherwise.
func (o *ImportsSearchImportFilesResp) GetTargetTables() []TableMatch {
	if o == nil || IsNil(o.TargetTables) {
		var ret []TableMatch
		return ret
	}
	return o.TargetTables
}

// GetTargetTablesOk returns a tuple with the TargetTables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportsSearchImportFilesResp) GetTargetTablesOk() ([]TableMatch, bool) {
	if o == nil || IsNil(o.TargetTables) {
		return nil, false
	}
	return o.TargetTables, true
}

// HasTargetTables returns a boolean if a field has been set.
func (o *ImportsSearchImportFilesResp) HasTargetTables() bool {
	if o != nil && !IsNil(o.TargetTables) {
		return true
	}

	return false
}

// SetTargetTables gets a reference to the given []TableMatch and assigns it to the TargetTables field.
func (o *ImportsSearchImportFilesResp) SetTargetTables(v []TableMatch) {
	o.TargetTables = v
}

// GetWarningMessage returns the WarningMessage field value if set, zero value otherwise.
func (o *ImportsSearchImportFilesResp) GetWarningMessage() string {
	if o == nil || IsNil(o.WarningMessage) {
		var ret string
		return ret
	}
	return *o.WarningMessage
}

// GetWarningMessageOk returns a tuple with the WarningMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportsSearchImportFilesResp) GetWarningMessageOk() (*string, bool) {
	if o == nil || IsNil(o.WarningMessage) {
		return nil, false
	}
	return o.WarningMessage, true
}

// HasWarningMessage returns a boolean if a field has been set.
func (o *ImportsSearchImportFilesResp) HasWarningMessage() bool {
	if o != nil && !IsNil(o.WarningMessage) {
		return true
	}

	return false
}

// SetWarningMessage gets a reference to the given string and assigns it to the WarningMessage field.
func (o *ImportsSearchImportFilesResp) SetWarningMessage(v string) {
	o.WarningMessage = &v
}

// GetBaseResp returns the BaseResp field value if set, zero value otherwise.
func (o *ImportsSearchImportFilesResp) GetBaseResp() BaseResp {
	if o == nil || IsNil(o.BaseResp) {
		var ret BaseResp
		return ret
	}
	return *o.BaseResp
}

// GetBaseRespOk returns a tuple with the BaseResp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportsSearchImportFilesResp) GetBaseRespOk() (*BaseResp, bool) {
	if o == nil || IsNil(o.BaseResp) {
		return nil, false
	}
	return o.BaseResp, true
}

// HasBaseResp returns a boolean if a field has been set.
func (o *ImportsSearchImportFilesResp) HasBaseResp() bool {
	if o != nil && !IsNil(o.BaseResp) {
		return true
	}

	return false
}

// SetBaseResp gets a reference to the given BaseResp and assigns it to the BaseResp field.
func (o *ImportsSearchImportFilesResp) SetBaseResp(v BaseResp) {
	o.BaseResp = &v
}

func (o ImportsSearchImportFilesResp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImportsSearchImportFilesResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TargetTables) {
		toSerialize["target_tables"] = o.TargetTables
	}
	if !IsNil(o.WarningMessage) {
		toSerialize["warning_message"] = o.WarningMessage
	}
	if !IsNil(o.BaseResp) {
		toSerialize["base_resp"] = o.BaseResp
	}
	return toSerialize, nil
}

type NullableImportsSearchImportFilesResp struct {
	value *ImportsSearchImportFilesResp
	isSet bool
}

func (v NullableImportsSearchImportFilesResp) Get() *ImportsSearchImportFilesResp {
	return v.value
}

func (v *NullableImportsSearchImportFilesResp) Set(val *ImportsSearchImportFilesResp) {
	v.value = val
	v.isSet = true
}

func (v NullableImportsSearchImportFilesResp) IsSet() bool {
	return v.isSet
}

func (v *NullableImportsSearchImportFilesResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImportsSearchImportFilesResp(val *ImportsSearchImportFilesResp) *NullableImportsSearchImportFilesResp {
	return &NullableImportsSearchImportFilesResp{value: val, isSet: true}
}

func (v NullableImportsSearchImportFilesResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImportsSearchImportFilesResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
