name: Branch Scene Test

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:
    inputs:
      testCase:
        description: "specify a case or skip to run all tests"
        default: ""
        required: false


jobs:
    branch-scene-test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install Go
          uses: actions/setup-go@v5
          with:
            go-version-file: './go.mod'

        - name: Restore Go modules cache
          uses: actions/cache@v4
          with:
            path: ~/go/pkg/mod
            key: go-${{ runner.os }}-${{ hashFiles('go.mod') }}
            restore-keys: |
              go-${{ runner.os }}-

        - name: Run tests
          run: |
            if [ -z ${{ github.event.inputs.testCase }} ]; then
              echo "Running all tests"
              go test -v sceneTest/branch/* -project-id 1372813089454562808 -config "${{ secrets.TEST_CONFIG }}"
            else
              echo "Running test ${{ github.event.inputs.testCase }}"
              go test -v sceneTest/branch/* -project-id 1372813089454562808 -config "${{ secrets.TEST_CONFIG }}" -run ${{ github.event.inputs.testCase }}
            fi
