name: Changefeed Scene Test

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0/30 * * * *'  # every 30 minutes
  workflow_dispatch:
    inputs:
      testCase:
        description: "specify a case or skip to run all tests"
        default: ""
        required: false


jobs:
    changefeed-scene-test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install Go
          uses: actions/setup-go@v5
          with:
            go-version-file: './go.mod'

        - name: Restore Go modules cache
          uses: actions/cache@v4
          with:
            path: ~/go/pkg/mod
            key: go-${{ runner.os }}-${{ hashFiles('go.mod') }}
            restore-keys: |
              go-${{ runner.os }}-

        - name: Run tests
          run: |
            if [ -z ${{ github.event.inputs.testCase }} ]; then
              echo "Running all tests"
              go run gotest.tools/gotestsum@latest --format standard-verbose -- sceneTest/cdc/* -timeout 20m -args --config "${{ secrets.TEST_CONFIG }}" --test.timeout 20m
            else
              echo "Running test ${{ github.event.inputs.testCase }}"
              go run gotest.tools/gotestsum@latest --format standard-verbose -- sceneTest/cdc/* -args --config "${{ secrets.TEST_CONFIG }}" --test.run ${{ github.event.inputs.testCase }}
            fi
