name: Connection Probe

on:
  pull_request:
  schedule:
    - cron: '0/5 * * * *'  # every 5 minutes
  workflow_dispatch:

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod tidy
        working-directory: ./connectionProbe

      - name: Run connection probe
        working-directory: ./connectionProbe
        run: |
          go run main.go --password "${{ secrets.PROBE_PASSWORD }}" --lark-webhook "${{ secrets.PROBE_LARK_WEBHOOK }}" --meta-dsn "${{ secrets.PROBE_META_DB_DSN }}" --action-url "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
