name: Import Console Api Test Alicloud

on:
  # Runs every two hours at odd hours (1, 3, 5, ...)
  schedule:
    - cron: "0 1-23/2 * * *"
  workflow_dispatch:
    inputs:
      testCase:
        description: "specify a case or skip to run all tests"
        default: ""
        required: false

jobs:
  import-console-api-test-alicloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'

      - name: Restore Go modules cache
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('go.mod') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Run tests
        run: |
          if [ -z ${{ github.event.inputs.testCase }} ]; then
            echo "Running all tests"
            go run gotest.tools/gotestsum@latest --format standard-verbose -- sceneTest/webImport/* -timeout 30m -args --cid 10748314250805687889 --pid 1372813089454562808 --oid 1372813089187041280 --config "${{ secrets.TEST_CONFIG_ALICLOUD }}" --test.timeout 30m --test.skip "TestS3Arn.*"
          else
            echo "Running test ${{ github.event.inputs.testCase }}"
            go run gotest.tools/gotestsum@latest --format standard-verbose -- sceneTest/webImport/* -args --cid 10748314250805687889 --pid 1372813089454562808 --oid 1372813089187041280 --config "${{ secrets.TEST_CONFIG_ALICLOUD }}" --test.run ${{ github.event.inputs.testCase }} 
          fi
